pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url "https://repository.liferay.com/nexus/content/repositories/public/" }
        maven { url "https://vungle.jfrog.io/artifactory/vungle-android-sdk" }
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://repository.liferay.com/nexus/content/repositories/public/" }
        maven { url "https://vungle.jfrog.io/artifactory/vungle-android-sdk" }
    }
}
rootProject.name = "Saayinsii Waliigalaa Kutaa 8ffaa"
include ':app'
